print ("Types of memes")
print (" ")
print ("Animemes") 
print ("Bootleg memes")
print ("Christian memes")
print ("Dank memes")
print ("Dark memes")
print ("Deep fried memes")
print ("History memes")
print ("Nuked memes")
print ("Offensive memes")
print ("Surreal memes")
print ("Wholesome memes")
noMore = input("Press [ENTER] key to exit")
# You are now informed of the types of memes