print ("Memes of 2019")
print ("This list is incomplete.")
print ("You can help by E X P A N D I N G it")
print ("\n")
print ("January 2019")
print ("\nLemon car")
print ("Queen dies")
print ("\n")
print ("February 2019")
print ("\n")
print ("March 2019")
print ("\n")
print ("April 2019")
print ("\n")
print ("May 2019")
print ("\n")
print ("June 2019")
print ("\n")
print ("July 2019")
print ("\n")
print ("August 2019")
print ("\n")
print ("September 2019")
print ("\n")
print ("October 2019")
print ("\n")
print ("November 2019")
print ("\n")
print ("December 2019")
noMore = input("Press [ENTER] key to quit")